title: Eva Nikolai
logo: "/images/image.png" 
description: >
  M.S. in Business Analytics Candidate at the University of Notre Dame, May 2023
  <br><br>
  <a href="https://www.linkedin.com/in/evanikolai">LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/eva-nikolai">GitHub Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
