title: Eva Nikolai
logo: "/images/image2.png" 
description: >
  MS Business Analytics | BBA Marketing
  <br><br>
  <a href="https://www.linkedin.com/in/evanikolai">LinkedIn</a>
  <br><br>
  <a href="https://github.com/eva-nikolai">GitHub</a>
  <br><br>
  <a href='Resume'>Resume</a>
theme: jekyll-theme-minimal
google_analytics: G-3LKSNCMGZD
