title: Eva Nikolai
logo: "/images/image.png" 
description: >
  MS Business Analytics | BBA Marketing
    <br><br>
  * 330-304-5907
    <br><br>
  * eva.e.nikolai@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/evanikolai">LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/eva-nikolai">GitHub Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0
