title: Eva Nikolai
logo: "/images/image.png" 
description: >
  MS Business Analytics | BBA Marketing
  <br><br>
  <a href="https://www.linkedin.com/in/evanikolai">LinkedIn Profile</a>
  <br><br>
  <a href="https://github.com/eva-nikolai">GitHub Profile</a>
  <br><br>
  <a href='Resume'>Resume</a>
theme: jekyll-theme-minimal
google_analytics: G-3LKSNCMGZD
