---
title: "Resume"
author: "Eva Nikolai"
date: "2023-07-11"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

[Back to Portfolio](index)

# EVA NIKOLAI 

330-304-5907 • eva.e.nikolai@gmail.com • https://www.linkedin.com/in/evanikolai/ • https://eva-nikolai.github.io/

### EDUCATION
**UNIVERSITY OF NOTRE DAME** 	Notre Dame, IN 
Master of Science in Business Analytics (MSBA) | *GPA: 3.7/ 4.0* |	May 2023

**KENT STATE UNIVERSITY**	Kent, OH
Bachelor of Business Administration | *GPA: 4.0/4.0* | Major in Marketing | Minor(s) in Economics, Finance	| May 2022
  
### PROFESSIONAL EXPERIENCE
**KENT STATE UNIVERSITY** 	Kent, OH <br>
**Athletics Marketing Intern** 	August 2021 - July 2022 <br>
*Guided 10 junior team members in executing competition and campus promotional campaigns and grassroots marketing, driving community engagement and improving the culture at revenue-generating sporting events <br>
*Conducted market research with 2 interns, exploring opportunities to integrate the NFT industry trend and analytics into the athletics marketing plan; Presented competitive analysis of NFTs in college athletics and actionable recommendations to optimize digital marketing, including the use of decision trees/ clustering algorithms to optimize audience targeting

**Division-I Women's Lacrosse Student-Athlete** 	August 2018 - May 2022 <br>
-	Represented Kent State student-athletes on 5 university and conference-wide strategic committees, holding various leadership positions and serving as a liaison between student-athletes and university and conference leadership  <br>
-	Led team to earn the IWLCA Community Awareness Award for DI women’s lacrosse serving as Community Service Coordinator, managing service activities, and connecting 38 athletes with volunteer opportunities in the local community

**SHERWIN-WILLIAMS COMPANY** 	Medina, OH <br>
**Management and Sales Intern** 	June 2021 - August 2021 <br>
-	Maximized customer satisfaction, utilizing product knowledge and expertise to creatively problem solve while consulting customers, identifying the best solutions to their specific needs while working in a fast-paced and hands-on environment  <br>
-	Designed a presentation of data-driven recommendations to target the "DIY" customer segment by collecting new client feedback and analyzing data from the CRM system in MS Excel, suggesting initiatives focused on customer experience 

### PROJECT EXPERIENCE
**UNIVERSITY OF NOTRE DAME MSBA PROJECTS**							 Notre Dame, IN <br>
**South Bend | Elkhart Regional Partnership (RP) Consulting Capstone, Project Manager**              January 2023 - May 2023 <br>
- Led a team of 5 to conduct analyses and deliver a custom BI dashboard, report, and PowerPoint to the executive team, identifying the key insights as the impact of income, education, and transportation on population retention in the region <br>
- Managed team communication and stakeholder meetings; Developed complex data management tool to ensure the efficient usage of APIs/ machine learning to extract large volumes of data and streamline future analyses and dashboard design

**Diversity, Equity & Inclusion (DEI) Grow the Good in Business Case Competition**	 	         	         April 2023 <br>
- Made top 10 of over 30 teams, producing a video pitch/slide deck of the Empowering Elderly Clients (EEC) initiative aimed to transform accessibility/safety in digital financial services, critical for the 65+ demographic at increased risk for fraud <br>
- Created 3 innovative solutions: AI tool with biometric ID tech to reduce fraud/ enhance user-friendliness; Customer surveys as KPI to track IT service effectiveness and ROI; Ambassador education program for empowerment in self-service banking

**Chicago Airport Performance Predictions**						       		       March 2023 <br>
* Collaborated with a team comparing Chicago ORD versus Chicago MDW’s departure delays; Predicted ORD to have more on-time departures, informing airline consumers’ purchase decisions and the airport’s need for operational improvements <br>
* Analyzed 10 years of data with various statistical models; Produced accurate and validated forecasts; Visualized findings in R, Python, and Tableau; Utilized storytelling techniques to deliver a results-focused presentation to prospective consumers

### LEADERSHIP & SERVICE ¬
**UNIVERSITY OF NOTRE DAME**									 Notre Dame, IN <br>
**MSBA Association (MSBAA), Secretary and Historian**					              August 2022 - May 2023 <br>
- Chaired networking/ volunteer events for MSBA, managing a $12,000 budget; Communicated program members’ concerns to ND faculty; Led meetings, ensuring productive discussions, maintaining detailed records, and tracking project deadlines

**Specialized Master’s Council (SMC), Representative and Parliamentarian**    	    	        September 2022 - May 2023 <br>
- Elected to represent MSBAA on the cross-functional team, collaborating with Mendoza liaisons to manage multiple projects simultaneously; Oversaw $20,000 budget and external funding; Agenda-planned and facilitated monthly meetings

### TECHNICAL SKILLS/ CERTIFICATIONS & INTERESTS 
**Technical Skills:** R, SQL, Python, Tableau, Azure, Figma, Microsoft Office/ Excel, Google Workspace <br>
**Certifications:**  Professional Sales Certificate - Kent State University, Google Analytics <br>
**Interests:** Travel, Fashion, Painting, Coaching lacrosse, Event planning, Trail running, Community service 
